### ISSUE TITLE
Sample Details

### ISSUE THREAD

**Issue by patripo123** [NDUWRDC/LIMS#53]
I suggest that we change the naming of the following;

Current                                 Proposed new name
Label                                      **Sample Name**
Qty                                           **Number of samples**
Sampling place                          Sample Source

**Comment by davidNDU** [comment]
'Number of samples' is not the same as 'Number of containers' or 'Number of bottles'.
For one sample there might be one or many bottles. For example the sample comes in a 1-liter bottle or in two 0.5-liter bottles. The volume would be 1 Liter in both cases but the amount of containers/bottles is 1 respectively 2.

**Comment by patripo123** [comment]
Okay. Makes so much sense

Patrick

**Comment by davidNDU** [comment]
![image](https://user-images.githubusercontent.com/40593993/105167878-58b5de00-5b2a-11eb-9341-54e49d86b952.png)

**Comment by patripo123** [comment]
Dear David,
Thank you for closing this off.

Best regards

Patrick
