### ISSUE TITLE
Corrective Action

### ISSUE THREAD

**Issue by patripo123** [NDUWRDC/LIMS#55]
This is a very vital aspect of the information management system when it comes to failing quality control. After adding Quality control Points, we need to have a way of correcting our results Data in case they fail due to the test method.

**Comment by davidNDU** [comment]
What is possible: after validation of a sample the sample can be set BACK TO DRAFT again. After this, the results may be changed. What is not taken care of: The old report is not kept as a copy. Maybe this module can help here: https://wiki.dolibarr.org/index.php/Module_Archives_/_Logs_Unalterable

**Comment by davidNDU** [comment]
Refering to ISO 17025: 7.5.2 Technical Records: the specification demands that the ammendments can be tracked to previous versions / the original observation. What needs to be implemented:
- keep the original data and files
- keep the amended data and files
- note the date of alteration
- indicate the altered aspects
- note the personnel responsible

**Comment by davidNDU** [comment]
One idea how to implement this:
1. Sample is Validated
2. Report is Printed with a time stamp in the file name
3. Sample details cannot be changed, MODIFY is not accessible
4. Sample is set BACK TO DRAFT
5. Version number of sample is increased by 1
6. Every change of the sample is logged as Event together with the version number
7. Sample is Validated
8. Report is Printed with a time stamp in the file name and with the list of Events for this version added to the bottom.
9. Repeat from 4. if required.

One of the difficulties: By default the report gets always overwritten by a new one is not kept.

**Comment by davidNDU** [comment]
https://github.com/NDUWRDC/LIMS/commit/e4518b50caf52edcf9d5d6193ff220d370e1d4ca
https://github.com/NDUWRDC/LIMS/commit/d061f27411d9883cfbff09efa4a3eeb5d70d402a

**Comment by patripo123** [comment]
Great Input David.

Patrick

**Comment by davidNDU** [comment]
https://github.com/NDUWRDC/LIMS/commit/d363ffbc4cfe58af48af4e6e5e6943f0faaa5d26

**Comment by davidNDU** [comment]
Test report now has list of modifications related to the sample and corresponding tests.
https://github.com/NDUWRDC/LIMS/commit/e98bba40b069b163dd2057010842a5880858462b
https://github.com/NDUWRDC/LIMS/commit/ee40f45698ddf6742c9c7cdef40aa48be6ee94d4
https://github.com/NDUWRDC/LIMS/commit/14e27e9c943496e25852762c5221f5445a156613
https://github.com/NDUWRDC/LIMS/commit/0df06ee9f8dc7e7c14df8f21c91b698787a0eb6d

![image](https://user-images.githubusercontent.com/40593993/106578007-1b9d1300-6550-11eb-9eb7-9696361b7620.png)
