### ISSUE TITLE
Report: Abnormality (Nonconformity) wrong number for line

### ISSUE THREAD

**Issue by davidNDU** [NDUWRDC/LIMS#65]
Seems the counter starts with 0

![grafik](https://user-images.githubusercontent.com/40593993/93465131-01410080-f8f3-11ea-9197-72f41d647f82.png)

**Comment by patripo123** [comment]
![description of the abnormality](https://user-images.githubusercontent.com/68999978/93594654-eb990d00-f9be-11ea-82ee-01c5af88e733.PNG)
![image](https://user-images.githubusercontent.com/68999978/93594673-f489de80-f9be-11ea-990c-6ed01c1770ea.png)

**Comment by patripo123** [comment]
Picture #1 let us change the comment on abnormality to "Test parameter Nitrate does not conform" something like this
Picture # 2 Lets is change the word "Description" to "Test parameter"

**Comment by davidNDU** [comment]
"Description" moved to issue #69
