### ISSUE TITLE
Report: column 'Standard' overflowing

### ISSUE THREAD

**Issue by davidNDU** [NDUWRDC/LIMS#67]
The column 'Standard' gets spilled over with letters because the width is fixed and there is no automatic carriage return. Another option would be to limit the text entered.

![grafik](https://user-images.githubusercontent.com/40593993/93465826-f8046380-f8f3-11ea-920e-adc50309bc80.png)

**Comment by patripo123** [comment]
I agree.  Can we may be try to summerize this? e.g. Photo Method?

**Comment by davidNDU** [comment]
![grafik](https://user-images.githubusercontent.com/40593993/93849226-4929a400-fcb4-11ea-901e-07aa769d7044.png)

**Comment by patripo123** [comment]
Dear David,
Thank you this input.


Let me try to input the results again.


Patrick
